name: Documentation book

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, test, and deploy docs
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.3
      MDBOOK_LINKCHECK_VERSION: 0.7.0
    steps:
      - uses: actions/checkout@v2
      - name: Cache mdbook & mdbook-linkcheck
        id: cache-mdbook
        uses: actions/cache@v2
        with:
          path: mdbook
          key: mdbook-${{ env.MDBOOK_VERSION }}-${{ env.MDBOOK_LINKCHECK_VERSION }}
      - name: Install mdbook & mdbook-linkcheck
        if: steps.cache-mdbook.outputs.cache-hit != 'true'
        run: |
          mkdir mdbook && cd mdbook
          curl -LsSf https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
          curl -LsSf https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v${MDBOOK_LINKCHECK_VERSION}/mdbook-linkcheck-v${MDBOOK_LINKCHECK_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
      - name: Add bins to PATH
        run: |
          echo $(pwd)/mdbook >> $GITHUB_PATH
      - run: mdbook build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
